version: '3.7'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: joth
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            TZ: UTC
            PGTZ: UTC
        ports:
            - 8888:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
